// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WebAPI/api_limit_2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ApiLimit2 {

  /// <summary>Holder for reflection information generated from WebAPI/api_limit_2.proto</summary>
  public static partial class ApiLimit2Reflection {

    #region Descriptor
    /// <summary>File descriptor for WebAPI/api_limit_2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApiLimit2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhXZWJBUEkvYXBpX2xpbWl0XzIucHJvdG8SC2FwaV9saW1pdF8yGhVjb21t",
            "b24vc2hhcmVkXzEucHJvdG8iIQoPQXBpTGltaXRSZXF1ZXN0Eg4KBmxpbWl0",
            "cxgBIAMoDSJ7Cg1BcGlMaW1pdEVudHJ5Eg0KBWxpbWl0GAEgASgNEhMKC3N0",
            "YXR1c19jb2RlGAIgASgNEg0KBXZhbHVlGAMgASgNEhIKCnBlcmlvZF9zZWMY",
            "BCABKA0SIwoLZGVzY3JpcHRpb24YBSABKAsyDi5zaGFyZWRfMS5UZXh0IkMK",
            "DkFwaUxpbWl0UmVwb3J0EjEKDWxpbWl0X2VudHJpZXMYASADKAsyGi5hcGlf",
            "bGltaXRfMi5BcGlMaW1pdEVudHJ5KsUeCghBcGlMaW1pdBIZChVBUElfTElN",
            "SVRfVU5TUEVDSUZJRUQQABIdChlBUElfTElNSVRfQ09OTkVDVElPTl9SQVRF",
            "EAESJAogQVBJX0xJTUlUX0NPTkNVUlJFTlRfU1VCU0VTU0lPTlMQAhIgChxB",
            "UElfTElNSVRfQ09OTkVDVElPTlNfUEVSX0lQEAMSNwozQVBJX0xJTUlUX1NP",
            "Q0tFVF9VTlJFQURZX1BFUklPRF9UT19DTE9TRV9DT05ORUNUSU9OEGQSIgoe",
            "QVBJX0xJTUlUX0NMSUVOVF9NRVNTQUdFU19SQVRFEG4SKAojQVBJX0xJTUlU",
            "X0lORk9STUFUSU9OX1JFUVVFU1RTX1JBVEUQyAESJQogQVBJX0xJTUlUX0FD",
            "Q09VTlRTX1JFUVVFU1RTX1JBVEUQ0gESLgopQVBJX0xJTUlUX1NZTUJPTF9S",
            "RVNPTFVUSU9OX1JFUVVFU1RTX1JBVEUQ3AESKwomQVBJX0xJTUlUX0xBU1Rf",
            "U1RBVEVNRU5UX0JBTEFOQ0VTX1JBVEUQ5gESKwomQVBJX0xJTUlUX0NVUlJF",
            "TkNZX1JBVEVTX1JFUVVFU1RTX1JBVEUQ8AESOQo0QVBJX0xJTUlUX1NFU1NJ",
            "T05fSU5GT1JNQVRJT05fUkVRVUVTVFNfSU5fUFJPQ0VTU0lORxD6ARIwCitB",
            "UElfTElNSVRfU0VTU0lPTl9JTkZPUk1BVElPTl9TVUJTQ1JJUFRJT05TEPsB",
            "EjcKMkFQSV9MSU1JVF9ISVNUT1JJQ0FMX09SREVSU19SRVFVRVNUU19JTl9Q",
            "Uk9DRVNTSU5HEIQCEiUKIEFQSV9MSU1JVF9ISVNUT1JJQ0FMX09SREVSU19E",
            "QVlTEIUCEjoKNUFQSV9MSU1JVF9PUFRJT05fTUFUVVJJVFlfTElTVF9SRVFV",
            "RVNUU19JTl9QUk9DRVNTSU5HEI4CEjEKLEFQSV9MSU1JVF9PUFRJT05fTUFU",
            "VVJJVFlfTElTVF9TVUJTQ1JJUFRJT05TEI8CEjYKMUFQSV9MSU1JVF9JTlNU",
            "UlVNRU5UX0dST1VQX1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQmAISLQooQVBJ",
            "X0xJTUlUX0lOU1RSVU1FTlRfR1JPVVBfU1VCU0NSSVBUSU9OUxCZAhI5CjRB",
            "UElfTElNSVRfQVRfVEhFX01PTkVZX1NUUklLRV9SRVFVRVNUU19JTl9QUk9D",
            "RVNTSU5HEKICEjAKK0FQSV9MSU1JVF9BVF9USEVfTU9ORVlfU1RSSUtFX1NV",
            "QlNDUklQVElPTlMQowISMAorQVBJX0xJTUlUX1NUUkFURUdZX0RFRklOSVRJ",
            "T05fUkVRVUVTVFNfUkFURRCsAhI4CjNBUElfTElNSVRfU0VTU0lPTl9USU1F",
            "X1JBTkdFX1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQtgISPAo3QVBJX0xJTUlU",
            "X1RSQURJTkdfREFZX1RJTUVfUkFOR0VfUkVRVUVTVFNfSU5fUFJPQ0VTU0lO",
            "RxDAAhI3CjJBUElfTElNSVRfT1JERVJfRU5USVRMRU1FTlRfUkVRVUVTVFNf",
            "SU5fUFJPQ0VTU0lORxDKAhI6CjVBUElfTElNSVRfU1lNQk9MX0NBVEVHT1JZ",
            "X0xJU1RfUkVRVUVTVFNfSU5fUFJPQ0VTU0lORxDUAhIxCixBUElfTElNSVRf",
            "U1lNQk9MX0NBVEVHT1JZX0xJU1RfU1VCU0NSSVBUSU9OUxDVAhI1CjBBUElf",
            "TElNSVRfU1lNQk9MX0NBVEVHT1JZX1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQ",
            "3gISLAonQVBJX0xJTUlUX1NZTUJPTF9DQVRFR09SWV9TVUJTQ1JJUFRJT05T",
            "EN8CEjEKLEFQSV9MSU1JVF9TWU1CT0xfTElTVF9SRVFVRVNUU19JTl9QUk9D",
            "RVNTSU5HEOgCEigKI0FQSV9MSU1JVF9TWU1CT0xfTElTVF9TVUJTQ1JJUFRJ",
            "T05TEOkCEiMKHkFQSV9MSU1JVF9TWU1CT0xfUkVRVUVTVFNfUkFURRDyAhIs",
            "CidBUElfTElNSVRfU1lNQk9MX1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQ8wIS",
            "Pgo5QVBJX0xJTUlUX0FMR09fU1RSQVRFR1lfREVGSU5JVElPTl9SRVFVRVNU",
            "U19JTl9QUk9DRVNTSU5HEPwCEkIKPUFQSV9MSU1JVF9BUElfTElNSVRTX1NV",
            "QlNDUklQVElPTlNfQU5EX1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQhgMSMQos",
            "QVBJX0xJTUlUX0NPTlRSSUJVVE9SX01FVEFEQVRBX1JFUVVFU1RTX1JBVEUQ",
            "kAMSSwpGQVBJX0xJTUlUX0JST0tFUkFHRV9UUkFESU5HX0ZFQVRVUkVfRU5U",
            "SVRMRU1FTlRfUkVRVUVTVFNfSU5fUFJPQ0VTU0lORxCaAxIpCiRBUElfTElN",
            "SVRfT1JERVJfU1RBVFVTX1JFUVVFU1RTX1JBVEUQpAMSKwomQVBJX0xJTUlU",
            "X1BST0RVQ1RfU0VBUkNIX1JFUVVFU1RTX1JBVEUQrgMSNAovQVBJX0xJTUlU",
            "X1BST0RVQ1RfU0VBUkNIX1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQrwMSRAo/",
            "QVBJX0xJTUlUX1NZTUJPTF9DQVRFR09SWV9MSVNUX0JZX0lOU1RSVU1FTlRf",
            "VFlQRV9SRVFVRVNUU19SQVRFELgDEk0KSEFQSV9MSU1JVF9TWU1CT0xfQ0FU",
            "RUdPUllfTElTVF9CWV9JTlNUUlVNRU5UX1RZUEVfUkVRVUVTVFNfSU5fUFJP",
            "Q0VTU0lORxC5AxIyCi1BUElfTElNSVRfTUFSS0VUX1NUQVRFX01FVEFEQVRB",
            "X1JFUVVFU1RTX1JBVEUQwgMSMgotQVBJX0xJTUlUX0lOU1RSVU1FTlRfREVG",
            "SU5JVElPTl9SRVFVRVNUU19SQVRFEMwDEjcKMkFQSV9MSU1JVF9FWENIQU5H",
            "RV9NRVRBREFUQV9SRVFVRVNUU19JTl9QUk9DRVNTSU5HENYDEi4KKUFQSV9M",
            "SU1JVF9FWENIQU5HRV9NRVRBREFUQV9TVUJTQ1JJUFRJT05TENcDEiUKIEFQ",
            "SV9MSU1JVF9UUkFERV9ST1VUSU5HX0FDQ09VTlRTENgEEiIKHUFQSV9MSU1J",
            "VF9UUkFERV9TVUJTQ1JJUFRJT05TEOIEEisKJkFQSV9MSU1JVF9UUkFERV9T",
            "VUJTQ1JJUFRJT05TX0FDQ09VTlRTEOMEEiIKHUFQSV9MSU1JVF9PUkRFUl9S",
            "RVFVRVNUU19SQVRFELwFEioKJUFQSV9MSU1JVF9PUkRFUl9SRVFVRVNUU19B",
            "Q0NPVU5UX1JBVEUQvQUSLAonQVBJX0xJTUlUX01BUktFVF9EQVRBX1NVQlND",
            "UklQVElPTl9SQVRFEKAGEigKI0FQSV9MSU1JVF9NQVJLRVRfREFUQV9TVUJT",
            "Q1JJUFRJT05TEKEGEjQKL0FQSV9MSU1JVF9NQVJLRVRfREFUQV9ERUxBWV9U",
            "T19DTE9TRV9DT05ORUNUSU9OEKoGEjAKK0FQSV9MSU1JVF9ISVNUT1JJQ0FM",
            "X1JFUVVFU1RTX0lOX1BST0NFU1NJTkcQ6AcSJwoiQVBJX0xJTUlUX0hJU1RP",
            "UklDQUxfU1VCU0NSSVBUSU9OUxDpBxIrCiZBUElfTElNSVRfVElNRV9BTkRf",
            "U0FMRVNfUkVRVUVTVFNfUkFURRDyBxIlCiBBUElfTElNSVRfVElNRV9CQVJf",
            "UkVRVUVTVFNfUkFURRD8BxI+CjlBUElfTElNSVRfVk9MVU1FX1BST0ZJTEVf",
            "UkVRVUVTVFNfQ09OVFJBQ1RfQU5EX1JBTkdFX1JBVEUQhggSKgolQVBJX0xJ",
            "TUlUX05PTl9USU1FRF9CQVJfUkVRVUVTVFNfUkFURRCQCBIiCh1BUElfTElN",
            "SVRfUlVMRVNfSU5fUFJPQ0VTU0lORxCwCRIYChNBUElfTElNSVRfUkVTRVJW",
            "RUQxEJQKEj8KOkFQSV9MSU1JVF9QVUJMSVNIX1VOUFVCTElTSF9QUkVWSUVX",
            "X0NPTlRSQUNUX1JFUVVFU1RTX1JBVEUQlQoSQQo8QVBJX0xJTUlUX1BVQkxJ",
            "U0hfVU5QVUJMSVNIX1BVQkxJU0hFRF9DT05UUkFDVF9SRVFVRVNUU19SQVRF",
            "EJYKEjQKL0FQSV9MSU1JVF9HRVRfU0VDVVJJVFlfUEFSQU1FVEVSU19SRVFV",
            "RVNUU19SQVRFEJcKEjQKL0FQSV9MSU1JVF9TRVRfU0VDVVJJVFlfUEFSQU1F",
            "VEVSU19SRVFVRVNUU19SQVRFEJgKEjQKL0FQSV9MSU1JVF9HRVRfQ09OVFJB",
            "Q1RfUEFSQU1FVEVSU19SRVFVRVNUU19SQVRFEJkKEioKJUFQSV9MSU1JVF9P",
            "VENfSU5TVEFOQ0VTX1NVQlNDUklQVElPTlMQ+AoSKAojQVBJX0xJTUlUX0hF",
            "REdFX0JPT0tTX1NVQlNDUklQVElPTlMQggsSLwoqQVBJX0xJTUlUX0hFREdF",
            "X0JPT0tfREVUQUlMU19SRVFVRVNUU19SQVRFEIwLEjgKM0FQSV9MSU1JVF9I",
            "RURHRV9CT09LX0RFVEFJTFNfUkVRVUVTVFNfSU5fUFJPQ0VTU0lORxCNCxIv",
            "CipBUElfTElNSVRfSEVER0VfQk9PS19ERVRBSUxTX1NVQlNDUklQVElPTlMQ",
            "jgsSMQosQVBJX0xJTUlUX09GRlNFVF9IRURHRV9CQUxBTkNFX1JFUVVFU1RT",
            "X1JBVEUQlgsSLQooQVBJX0xJTUlUX0NIQU5HRV9PVENfU1RBVEVfUkVRVUVT",
            "VFNfUkFURRCgCxIsCidBUElfTElNSVRfRklMTF9DQVNIX09SREVSX1JFUVVF",
            "U1RTX1JBVEUQqgsSKAojQVBJX0xJTUlUX1JGUV9SRVFVRVNUU19BQ0NPVU5U",
            "X1JBVEUQ3AsSLwoqQVBJX0xJTUlUX09QVElPTl9DQUxDVUxBVElPTl9SRVFV",
            "RVNUU19SQVRFEMAMEi8KKkFQSV9MSU1JVF9PUFRJT05fQ0FMQ1VMQVRJT05f",
            "U1VCU0NSSVBUSU9OUxDBDBItCihBUElfTElNSVRfUkZRX1NVQlNDUklQVElP",
            "Tl9SRVFVRVNUU19SQVRFEKQNKsMBChdBcGlMaW1pdEVudHJ5U3RhdHVzQ29k",
            "ZRIrCidBUElfTElNSVRfRU5UUllfU1RBVFVTX0NPREVfVU5TUEVDSUZJRUQQ",
            "ABInCiNBUElfTElNSVRfRU5UUllfU1RBVFVTX0NPREVfU1VDQ0VTUxABEicK",
            "I0FQSV9MSU1JVF9FTlRSWV9TVEFUVVNfQ09ERV9GQUlMVVJFEGUSKQolQVBJ",
            "X0xJTUlUX0VOVFJZX1NUQVRVU19DT0RFX05PVF9GT1VORBBo"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Shared1.Shared1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ApiLimit2.ApiLimit), typeof(global::ApiLimit2.ApiLimitEntryStatusCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ApiLimit2.ApiLimitRequest), global::ApiLimit2.ApiLimitRequest.Parser, new[]{ "Limits" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ApiLimit2.ApiLimitEntry), global::ApiLimit2.ApiLimitEntry.Parser, new[]{ "Limit", "StatusCode", "Value", "PeriodSec", "Description" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ApiLimit2.ApiLimitReport), global::ApiLimit2.ApiLimitReport.Parser, new[]{ "LimitEntries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Naming convention:
  /// *_RATE - maximum number of messages of the corresponding type
  ///     per output period. Messages exceeding the limit are rejected.
  /// *_REQUESTS_IN_PROCESSING - maximum number of requests of
  ///     the corresponding type in processing till a snapshot received.
  ///     Messages exceeding the limit are rejected.
  /// *_SUBSCRIPTIONS - maximum number of subscriptions for updates.
  ///     Messages exceeding the limit are rejected.
  /// *_TO_CLOSE_CONNECTION limit violation leads to
  ///     user disconnection from the server.
  /// </summary>
  public enum ApiLimit {
    /// <summary>
    /// Limit type unspecifed and must be ignored.
    /// </summary>
    [pbr::OriginalName("API_LIMIT_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Generic and session limits (1 - 99)
    /// Max connection rate from one IP address
    /// </summary>
    [pbr::OriginalName("API_LIMIT_CONNECTION_RATE")] ConnectionRate = 1,
    /// <summary>
    /// Max concurrent subsession per user
    /// </summary>
    [pbr::OriginalName("API_LIMIT_CONCURRENT_SUBSESSIONS")] ConcurrentSubsessions = 2,
    /// <summary>
    /// Number of maximum allowed simultaneous connections from single IP address
    /// </summary>
    [pbr::OriginalName("API_LIMIT_CONNECTIONS_PER_IP")] ConnectionsPerIp = 3,
    /// <summary>
    /// Generic message related limits (100-199)
    /// Maximum allowed duration (in seconds) of WebSocket unavailability
    /// for outgoing messages.
    /// </summary>
    [pbr::OriginalName("API_LIMIT_SOCKET_UNREADY_PERIOD_TO_CLOSE_CONNECTION")] SocketUnreadyPeriodToCloseConnection = 100,
    [pbr::OriginalName("API_LIMIT_CLIENT_MESSAGES_RATE")] ClientMessagesRate = 110,
    /// <summary>
    /// Information request limits (200-599)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_INFORMATION_REQUESTS_RATE")] InformationRequestsRate = 200,
    [pbr::OriginalName("API_LIMIT_ACCOUNTS_REQUESTS_RATE")] AccountsRequestsRate = 210,
    [pbr::OriginalName("API_LIMIT_SYMBOL_RESOLUTION_REQUESTS_RATE")] SymbolResolutionRequestsRate = 220,
    [pbr::OriginalName("API_LIMIT_LAST_STATEMENT_BALANCES_RATE")] LastStatementBalancesRate = 230,
    [pbr::OriginalName("API_LIMIT_CURRENCY_RATES_REQUESTS_RATE")] CurrencyRatesRequestsRate = 240,
    [pbr::OriginalName("API_LIMIT_SESSION_INFORMATION_REQUESTS_IN_PROCESSING")] SessionInformationRequestsInProcessing = 250,
    [pbr::OriginalName("API_LIMIT_SESSION_INFORMATION_SUBSCRIPTIONS")] SessionInformationSubscriptions = 251,
    [pbr::OriginalName("API_LIMIT_HISTORICAL_ORDERS_REQUESTS_IN_PROCESSING")] HistoricalOrdersRequestsInProcessing = 260,
    /// <summary>
    /// Maximum allowed days back from now for historical orders requests.
    /// Exceeding fails requests.
    /// </summary>
    [pbr::OriginalName("API_LIMIT_HISTORICAL_ORDERS_DAYS")] HistoricalOrdersDays = 261,
    [pbr::OriginalName("API_LIMIT_OPTION_MATURITY_LIST_REQUESTS_IN_PROCESSING")] OptionMaturityListRequestsInProcessing = 270,
    [pbr::OriginalName("API_LIMIT_OPTION_MATURITY_LIST_SUBSCRIPTIONS")] OptionMaturityListSubscriptions = 271,
    [pbr::OriginalName("API_LIMIT_INSTRUMENT_GROUP_REQUESTS_IN_PROCESSING")] InstrumentGroupRequestsInProcessing = 280,
    [pbr::OriginalName("API_LIMIT_INSTRUMENT_GROUP_SUBSCRIPTIONS")] InstrumentGroupSubscriptions = 281,
    [pbr::OriginalName("API_LIMIT_AT_THE_MONEY_STRIKE_REQUESTS_IN_PROCESSING")] AtTheMoneyStrikeRequestsInProcessing = 290,
    [pbr::OriginalName("API_LIMIT_AT_THE_MONEY_STRIKE_SUBSCRIPTIONS")] AtTheMoneyStrikeSubscriptions = 291,
    [pbr::OriginalName("API_LIMIT_STRATEGY_DEFINITION_REQUESTS_RATE")] StrategyDefinitionRequestsRate = 300,
    [pbr::OriginalName("API_LIMIT_SESSION_TIME_RANGE_REQUESTS_IN_PROCESSING")] SessionTimeRangeRequestsInProcessing = 310,
    [pbr::OriginalName("API_LIMIT_TRADING_DAY_TIME_RANGE_REQUESTS_IN_PROCESSING")] TradingDayTimeRangeRequestsInProcessing = 320,
    [pbr::OriginalName("API_LIMIT_ORDER_ENTITLEMENT_REQUESTS_IN_PROCESSING")] OrderEntitlementRequestsInProcessing = 330,
    [pbr::OriginalName("API_LIMIT_SYMBOL_CATEGORY_LIST_REQUESTS_IN_PROCESSING")] SymbolCategoryListRequestsInProcessing = 340,
    [pbr::OriginalName("API_LIMIT_SYMBOL_CATEGORY_LIST_SUBSCRIPTIONS")] SymbolCategoryListSubscriptions = 341,
    [pbr::OriginalName("API_LIMIT_SYMBOL_CATEGORY_REQUESTS_IN_PROCESSING")] SymbolCategoryRequestsInProcessing = 350,
    [pbr::OriginalName("API_LIMIT_SYMBOL_CATEGORY_SUBSCRIPTIONS")] SymbolCategorySubscriptions = 351,
    [pbr::OriginalName("API_LIMIT_SYMBOL_LIST_REQUESTS_IN_PROCESSING")] SymbolListRequestsInProcessing = 360,
    [pbr::OriginalName("API_LIMIT_SYMBOL_LIST_SUBSCRIPTIONS")] SymbolListSubscriptions = 361,
    [pbr::OriginalName("API_LIMIT_SYMBOL_REQUESTS_RATE")] SymbolRequestsRate = 370,
    [pbr::OriginalName("API_LIMIT_SYMBOL_REQUESTS_IN_PROCESSING")] SymbolRequestsInProcessing = 371,
    [pbr::OriginalName("API_LIMIT_ALGO_STRATEGY_DEFINITION_REQUESTS_IN_PROCESSING")] AlgoStrategyDefinitionRequestsInProcessing = 380,
    [pbr::OriginalName("API_LIMIT_API_LIMITS_SUBSCRIPTIONS_AND_REQUESTS_IN_PROCESSING")] ApiLimitsSubscriptionsAndRequestsInProcessing = 390,
    [pbr::OriginalName("API_LIMIT_CONTRIBUTOR_METADATA_REQUESTS_RATE")] ContributorMetadataRequestsRate = 400,
    [pbr::OriginalName("API_LIMIT_BROKERAGE_TRADING_FEATURE_ENTITLEMENT_REQUESTS_IN_PROCESSING")] BrokerageTradingFeatureEntitlementRequestsInProcessing = 410,
    [pbr::OriginalName("API_LIMIT_ORDER_STATUS_REQUESTS_RATE")] OrderStatusRequestsRate = 420,
    [pbr::OriginalName("API_LIMIT_PRODUCT_SEARCH_REQUESTS_RATE")] ProductSearchRequestsRate = 430,
    [pbr::OriginalName("API_LIMIT_PRODUCT_SEARCH_REQUESTS_IN_PROCESSING")] ProductSearchRequestsInProcessing = 431,
    [pbr::OriginalName("API_LIMIT_SYMBOL_CATEGORY_LIST_BY_INSTRUMENT_TYPE_REQUESTS_RATE")] SymbolCategoryListByInstrumentTypeRequestsRate = 440,
    [pbr::OriginalName("API_LIMIT_SYMBOL_CATEGORY_LIST_BY_INSTRUMENT_TYPE_REQUESTS_IN_PROCESSING")] SymbolCategoryListByInstrumentTypeRequestsInProcessing = 441,
    [pbr::OriginalName("API_LIMIT_MARKET_STATE_METADATA_REQUESTS_RATE")] MarketStateMetadataRequestsRate = 450,
    [pbr::OriginalName("API_LIMIT_INSTRUMENT_DEFINITION_REQUESTS_RATE")] InstrumentDefinitionRequestsRate = 460,
    [pbr::OriginalName("API_LIMIT_EXCHANGE_METADATA_REQUESTS_IN_PROCESSING")] ExchangeMetadataRequestsInProcessing = 470,
    [pbr::OriginalName("API_LIMIT_EXCHANGE_METADATA_SUBSCRIPTIONS")] ExchangeMetadataSubscriptions = 471,
    /// <summary>
    /// TradeSubscription (600-699)
    /// Maximum account number per trader to process
    /// </summary>
    [pbr::OriginalName("API_LIMIT_TRADE_ROUTING_ACCOUNTS")] TradeRoutingAccounts = 600,
    [pbr::OriginalName("API_LIMIT_TRADE_SUBSCRIPTIONS")] TradeSubscriptions = 610,
    /// <summary>
    /// Maximum accounts to subscribe to
    /// </summary>
    [pbr::OriginalName("API_LIMIT_TRADE_SUBSCRIPTIONS_ACCOUNTS")] TradeSubscriptionsAccounts = 611,
    /// <summary>
    /// Order request (700-799)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_ORDER_REQUESTS_RATE")] OrderRequestsRate = 700,
    /// <summary>
    /// Rate per account
    /// </summary>
    [pbr::OriginalName("API_LIMIT_ORDER_REQUESTS_ACCOUNT_RATE")] OrderRequestsAccountRate = 701,
    /// <summary>
    /// Market data subscription (800 - 899)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_MARKET_DATA_SUBSCRIPTION_RATE")] MarketDataSubscriptionRate = 800,
    [pbr::OriginalName("API_LIMIT_MARKET_DATA_SUBSCRIPTIONS")] MarketDataSubscriptions = 801,
    /// <summary>
    /// Market data quotes delay threshold (in seconds)
    /// after which user will be disconnected.
    /// </summary>
    [pbr::OriginalName("API_LIMIT_MARKET_DATA_DELAY_TO_CLOSE_CONNECTION")] MarketDataDelayToCloseConnection = 810,
    /// <summary>
    /// Historical requests (1000-1299)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_HISTORICAL_REQUESTS_IN_PROCESSING")] HistoricalRequestsInProcessing = 1000,
    [pbr::OriginalName("API_LIMIT_HISTORICAL_SUBSCRIPTIONS")] HistoricalSubscriptions = 1001,
    [pbr::OriginalName("API_LIMIT_TIME_AND_SALES_REQUESTS_RATE")] TimeAndSalesRequestsRate = 1010,
    [pbr::OriginalName("API_LIMIT_TIME_BAR_REQUESTS_RATE")] TimeBarRequestsRate = 1020,
    /// <summary>
    /// Per contract and time range, not per connection
    /// </summary>
    [pbr::OriginalName("API_LIMIT_VOLUME_PROFILE_REQUESTS_CONTRACT_AND_RANGE_RATE")] VolumeProfileRequestsContractAndRangeRate = 1030,
    [pbr::OriginalName("API_LIMIT_NON_TIMED_BAR_REQUESTS_RATE")] NonTimedBarRequestsRate = 1040,
    /// <summary>
    /// Rules requests (1200-1299)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_RULES_IN_PROCESSING")] RulesInProcessing = 1200,
    /// <summary>
    /// Metadata admin request (1300-1399)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_RESERVED1")] Reserved1 = 1300,
    [pbr::OriginalName("API_LIMIT_PUBLISH_UNPUBLISH_PREVIEW_CONTRACT_REQUESTS_RATE")] PublishUnpublishPreviewContractRequestsRate = 1301,
    [pbr::OriginalName("API_LIMIT_PUBLISH_UNPUBLISH_PUBLISHED_CONTRACT_REQUESTS_RATE")] PublishUnpublishPublishedContractRequestsRate = 1302,
    [pbr::OriginalName("API_LIMIT_GET_SECURITY_PARAMETERS_REQUESTS_RATE")] GetSecurityParametersRequestsRate = 1303,
    [pbr::OriginalName("API_LIMIT_SET_SECURITY_PARAMETERS_REQUESTS_RATE")] SetSecurityParametersRequestsRate = 1304,
    [pbr::OriginalName("API_LIMIT_GET_CONTRACT_PARAMETERS_REQUESTS_RATE")] GetContractParametersRequestsRate = 1305,
    /// <summary>
    /// OTC request (1400-1499)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_OTC_INSTANCES_SUBSCRIPTIONS")] OtcInstancesSubscriptions = 1400,
    [pbr::OriginalName("API_LIMIT_HEDGE_BOOKS_SUBSCRIPTIONS")] HedgeBooksSubscriptions = 1410,
    [pbr::OriginalName("API_LIMIT_HEDGE_BOOK_DETAILS_REQUESTS_RATE")] HedgeBookDetailsRequestsRate = 1420,
    [pbr::OriginalName("API_LIMIT_HEDGE_BOOK_DETAILS_REQUESTS_IN_PROCESSING")] HedgeBookDetailsRequestsInProcessing = 1421,
    [pbr::OriginalName("API_LIMIT_HEDGE_BOOK_DETAILS_SUBSCRIPTIONS")] HedgeBookDetailsSubscriptions = 1422,
    [pbr::OriginalName("API_LIMIT_OFFSET_HEDGE_BALANCE_REQUESTS_RATE")] OffsetHedgeBalanceRequestsRate = 1430,
    [pbr::OriginalName("API_LIMIT_CHANGE_OTC_STATE_REQUESTS_RATE")] ChangeOtcStateRequestsRate = 1440,
    [pbr::OriginalName("API_LIMIT_FILL_CASH_ORDER_REQUESTS_RATE")] FillCashOrderRequestsRate = 1450,
    /// <summary>
    /// RFQ request (1500-1599)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_RFQ_REQUESTS_ACCOUNT_RATE")] RfqRequestsAccountRate = 1500,
    /// <summary>
    /// Option calculation request (1600-1699)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_OPTION_CALCULATION_REQUESTS_RATE")] OptionCalculationRequestsRate = 1600,
    [pbr::OriginalName("API_LIMIT_OPTION_CALCULATION_SUBSCRIPTIONS")] OptionCalculationSubscriptions = 1601,
    /// <summary>
    /// RFQ subscription request (1700-1799)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_RFQ_SUBSCRIPTION_REQUESTS_RATE")] RfqSubscriptionRequestsRate = 1700,
  }

  public enum ApiLimitEntryStatusCode {
    /// <summary>
    /// Entry not specified and must be ignored.
    /// </summary>
    [pbr::OriginalName("API_LIMIT_ENTRY_STATUS_CODE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Value is populated.
    /// </summary>
    [pbr::OriginalName("API_LIMIT_ENTRY_STATUS_CODE_SUCCESS")] Success = 1,
    /// <summary>
    /// Failure codes (100+)
    /// General failure, client should use the default value
    /// (from proto file comments, descriptions, etc.)
    /// </summary>
    [pbr::OriginalName("API_LIMIT_ENTRY_STATUS_CODE_FAILURE")] Failure = 101,
    /// <summary>
    /// Limit type not found or already deleted (value is not restricted).
    /// </summary>
    [pbr::OriginalName("API_LIMIT_ENTRY_STATUS_CODE_NOT_FOUND")] NotFound = 104,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApiLimitRequest : pb::IMessage<ApiLimitRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiLimitRequest> _parser = new pb::MessageParser<ApiLimitRequest>(() => new ApiLimitRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApiLimitRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ApiLimit2.ApiLimit2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitRequest(ApiLimitRequest other) : this() {
      limits_ = other.limits_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitRequest Clone() {
      return new ApiLimitRequest(this);
    }

    /// <summary>Field number for the "limits" field.</summary>
    public const int LimitsFieldNumber = 1;
    private static readonly pb::FieldCodec<uint> _repeated_limits_codec
        = pb::FieldCodec.ForUInt32(8);
    private readonly pbc::RepeatedField<uint> limits_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// Limit types to request.
    /// This field is associated with ApiLimit enum type.
    /// If empty, all supported limits will be returned.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Limits {
      get { return limits_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApiLimitRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApiLimitRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!limits_.Equals(other.limits_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= limits_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      limits_.WriteTo(output, _repeated_limits_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      limits_.WriteTo(ref output, _repeated_limits_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += limits_.CalculateSize(_repeated_limits_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApiLimitRequest other) {
      if (other == null) {
        return;
      }
      limits_.Add(other.limits_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            limits_.AddEntriesFrom(input, _repeated_limits_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            limits_.AddEntriesFrom(ref input, _repeated_limits_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApiLimitEntry : pb::IMessage<ApiLimitEntry>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiLimitEntry> _parser = new pb::MessageParser<ApiLimitEntry>(() => new ApiLimitEntry());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApiLimitEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ApiLimit2.ApiLimit2Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitEntry(ApiLimitEntry other) : this() {
      _hasBits0 = other._hasBits0;
      limit_ = other.limit_;
      statusCode_ = other.statusCode_;
      value_ = other.value_;
      periodSec_ = other.periodSec_;
      description_ = other.description_ != null ? other.description_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitEntry Clone() {
      return new ApiLimitEntry(this);
    }

    /// <summary>Field number for the "limit" field.</summary>
    public const int LimitFieldNumber = 1;
    private readonly static uint LimitDefaultValue = 0;

    private uint limit_;
    /// <summary>
    /// Limit type.
    /// This field is associated with ApiLimit enum type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Limit {
      get { if ((_hasBits0 & 1) != 0) { return limit_; } else { return LimitDefaultValue; } }
      set {
        _hasBits0 |= 1;
        limit_ = value;
      }
    }
    /// <summary>Gets whether the "limit" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLimit {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "limit" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLimit() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "status_code" field.</summary>
    public const int StatusCodeFieldNumber = 2;
    private readonly static uint StatusCodeDefaultValue = 0;

    private uint statusCode_;
    /// <summary>
    /// Result status of the request.
    /// This field is associated with ApiLimitEntryStatusCode enum type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StatusCode {
      get { if ((_hasBits0 & 2) != 0) { return statusCode_; } else { return StatusCodeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        statusCode_ = value;
      }
    }
    /// <summary>Gets whether the "status_code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStatusCode {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "status_code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStatusCode() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private readonly static uint ValueDefaultValue = 0;

    private uint value_;
    /// <summary>
    /// Limit value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Value {
      get { if ((_hasBits0 & 4) != 0) { return value_; } else { return ValueDefaultValue; } }
      set {
        _hasBits0 |= 4;
        value_ = value;
      }
    }
    /// <summary>Gets whether the "value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasValue {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValue() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "period_sec" field.</summary>
    public const int PeriodSecFieldNumber = 4;
    private readonly static uint PeriodSecDefaultValue = 0;

    private uint periodSec_;
    /// <summary>
    /// Populated if the limit is a rate = value / period_sec.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PeriodSec {
      get { if ((_hasBits0 & 8) != 0) { return periodSec_; } else { return PeriodSecDefaultValue; } }
      set {
        _hasBits0 |= 8;
        periodSec_ = value;
      }
    }
    /// <summary>Gets whether the "period_sec" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPeriodSec {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "period_sec" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPeriodSec() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 5;
    private global::Shared1.Text description_;
    /// <summary>
    /// Limit description.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Shared1.Text Description {
      get { return description_; }
      set {
        description_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApiLimitEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApiLimitEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Limit != other.Limit) return false;
      if (StatusCode != other.StatusCode) return false;
      if (Value != other.Value) return false;
      if (PeriodSec != other.PeriodSec) return false;
      if (!object.Equals(Description, other.Description)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLimit) hash ^= Limit.GetHashCode();
      if (HasStatusCode) hash ^= StatusCode.GetHashCode();
      if (HasValue) hash ^= Value.GetHashCode();
      if (HasPeriodSec) hash ^= PeriodSec.GetHashCode();
      if (description_ != null) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLimit) {
        output.WriteRawTag(8);
        output.WriteUInt32(Limit);
      }
      if (HasStatusCode) {
        output.WriteRawTag(16);
        output.WriteUInt32(StatusCode);
      }
      if (HasValue) {
        output.WriteRawTag(24);
        output.WriteUInt32(Value);
      }
      if (HasPeriodSec) {
        output.WriteRawTag(32);
        output.WriteUInt32(PeriodSec);
      }
      if (description_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLimit) {
        output.WriteRawTag(8);
        output.WriteUInt32(Limit);
      }
      if (HasStatusCode) {
        output.WriteRawTag(16);
        output.WriteUInt32(StatusCode);
      }
      if (HasValue) {
        output.WriteRawTag(24);
        output.WriteUInt32(Value);
      }
      if (HasPeriodSec) {
        output.WriteRawTag(32);
        output.WriteUInt32(PeriodSec);
      }
      if (description_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLimit) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Limit);
      }
      if (HasStatusCode) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StatusCode);
      }
      if (HasValue) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Value);
      }
      if (HasPeriodSec) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PeriodSec);
      }
      if (description_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApiLimitEntry other) {
      if (other == null) {
        return;
      }
      if (other.HasLimit) {
        Limit = other.Limit;
      }
      if (other.HasStatusCode) {
        StatusCode = other.StatusCode;
      }
      if (other.HasValue) {
        Value = other.Value;
      }
      if (other.HasPeriodSec) {
        PeriodSec = other.PeriodSec;
      }
      if (other.description_ != null) {
        if (description_ == null) {
          Description = new global::Shared1.Text();
        }
        Description.MergeFrom(other.Description);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Limit = input.ReadUInt32();
            break;
          }
          case 16: {
            StatusCode = input.ReadUInt32();
            break;
          }
          case 24: {
            Value = input.ReadUInt32();
            break;
          }
          case 32: {
            PeriodSec = input.ReadUInt32();
            break;
          }
          case 42: {
            if (description_ == null) {
              Description = new global::Shared1.Text();
            }
            input.ReadMessage(Description);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Limit = input.ReadUInt32();
            break;
          }
          case 16: {
            StatusCode = input.ReadUInt32();
            break;
          }
          case 24: {
            Value = input.ReadUInt32();
            break;
          }
          case 32: {
            PeriodSec = input.ReadUInt32();
            break;
          }
          case 42: {
            if (description_ == null) {
              Description = new global::Shared1.Text();
            }
            input.ReadMessage(Description);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ApiLimitReport : pb::IMessage<ApiLimitReport>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ApiLimitReport> _parser = new pb::MessageParser<ApiLimitReport>(() => new ApiLimitReport());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ApiLimitReport> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ApiLimit2.ApiLimit2Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitReport() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitReport(ApiLimitReport other) : this() {
      limitEntries_ = other.limitEntries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ApiLimitReport Clone() {
      return new ApiLimitReport(this);
    }

    /// <summary>Field number for the "limit_entries" field.</summary>
    public const int LimitEntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ApiLimit2.ApiLimitEntry> _repeated_limitEntries_codec
        = pb::FieldCodec.ForMessage(10, global::ApiLimit2.ApiLimitEntry.Parser);
    private readonly pbc::RepeatedField<global::ApiLimit2.ApiLimitEntry> limitEntries_ = new pbc::RepeatedField<global::ApiLimit2.ApiLimitEntry>();
    /// <summary>
    /// Limit output entries.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ApiLimit2.ApiLimitEntry> LimitEntries {
      get { return limitEntries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ApiLimitReport);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ApiLimitReport other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!limitEntries_.Equals(other.limitEntries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= limitEntries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      limitEntries_.WriteTo(output, _repeated_limitEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      limitEntries_.WriteTo(ref output, _repeated_limitEntries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += limitEntries_.CalculateSize(_repeated_limitEntries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ApiLimitReport other) {
      if (other == null) {
        return;
      }
      limitEntries_.Add(other.limitEntries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            limitEntries_.AddEntriesFrom(input, _repeated_limitEntries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            limitEntries_.AddEntriesFrom(ref input, _repeated_limitEntries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
